name 'evenup-ec2_tools'
version '1.3.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages the ec2-tools.'
description 'Installs the amazon ec2-tools command line package.'
project_page 'https://github.com/evenup/evenup-ec2_tools'
dependency 'evenup/java', '>= 0.0.3'
